### PR TITLE
  Optimizations in linear polynomial transformations and bug fixes

### PR DESCRIPTION
**Pull request by ssmiler**
Issue #70: Bug in writeContextBase function.
Closing brackets miss when context.zMStar.numOfGens() is zero.

### CODE REVIEW

**Comment by ssmiler** [comment]
Optimizations in linear polynomial transformations

**Comment by ssmiler** [comment]
Implemented optimizations described in http://eprint.iacr.org/2015/1199

**Comment by thEpisode** [comment]
Awesome work, why isn't merged?

**Comment by shaih** [comment]
It is merged now

**Comment by ssmiler** [comment]
Hi, no conflicts with master now.

**Comment by faberga** [comment]
Closed as merged back in 2018

**Pull request closed without merging**
