### PR TITLE
Test doc

### PR DESCRIPTION
**Pull request by XuesongHu**
1. Correct a path to run test.
2. Formatting TESTS.md

### CODE REVIEW

**Comment by faberga** [comment]
Hi @XuesongHu. Thank you for your PR contribution.
HElib has recently been updated to a new release. Can I ask you to rebase to the head of the master branch and resolve the conflicts, please?

Thank you,
Flavio

**Comment by faberga** [comment]
Hi @XuesongHu.
Have you had time to rebase your forks and check for the conflicts?

Thank you,
Flavio

**Comment by XuesongHu** [comment]
@faberga The merge-conflict has been resolved.

**Comment by faberga** [comment]
Hi @XuesongHu 
In HElib v1.1.0, we have done a review/rewrite of the documentation for the tests which made the PR obsolete.
I'm closing this PR, but I am looking forward for your next contributions.

Thank you,
Flavio

**Pull request closed without merging**
