### PR TITLE
Fix misspellings

### PR DESCRIPTION
**Pull request by noelniles**
This commit fixes some typos in the comments and documentation.

### CODE REVIEW

**Comment by faberga** [comment]
@noelniles Can you please rebase your forked branch with our latest commit, to resolve the conflicts, and resubmit your pull request, please?
Thank you.

**Comment by noelniles** [comment]
@faberga done.

**Comment by faberga** [comment]
@noelniles There seems to be some large changes to src/misc/FHE.h and other changes to src/recryption.cpp beyond just the typos. It is likely to be lack of sync between you fork and the current master.

Anyway, we are about to push a change that splits FHE.h, can I ask you to hang on for a few days before rebasing your fork, please?

**Review by faberga — CHANGES_REQUESTED** [review]
@noelniles Thank you for your PR contribution.
HElib has moved a long way since you opened your PR. Can I ask you to rebase to the head of the master branch and resolve the all conflicts, please?

Thank you,
Flavio

**Comment by faberga** [comment]
@noelniles Thank you for your PR contribution.
I am closing this PR as it has been superseded by a large refactoring of HElib.

**Pull request closed without merging**
