### PR TITLE
Suggested fix for #129 (FindM now checks that nSlots is >= no. of slots asked for)

### PR DESCRIPTION
**Pull request by AlexanderViand**
Relates to issue #129 
I'm not sure if my changes are actually sufficient to ensure that a good and suitable m is chosen, so I'd appreciate some feedback

### CODE REVIEW

**Comment by faberga** [comment]
@esteffin Can you check this for me, please?

**Comment by faberga** [comment]
Hi @AlexanderViand, Thank you for your contribution.

HElib has come a long way since you raised this PR. Would you be able to rebase your fork and let us know if you still consider   your PR applicable, please?

Thank you,
Flavio

**Comment by AlexanderViand** [comment]
@faberga Sure, I've rebased it to the current head, it looks like apart from the changes due to the move from Levels `L` to `nBits`, there haven't really been any updates to the logic of `FindM` so the original bug reported in #129 should still be there.

However, as noted in the issue, my fix was far from complete - I'm pretty sure there's a chance it won't terminate if the user tries to find impossible parameters, and there seem to be additional cases where `FindM`  fails to produce correct and secure parameters. 

I guess the "correct" way forward here would be to unit test `FindM` more thoroughly to identify what it does when it fails to find parameters satisfying the requirements. However, I haven't touched HElib in a while and I'm currently quite busy.

**Comment by faberga** [comment]
Converting this PR to a draft, so it can be worked on when @AlexanderViand is available perform a thorough test.

**Pull request closed without merging**
