### PR TITLE
Small performance improvements and cleanup

### PR DESCRIPTION
**Pull request by dimhotepus**
* `size_t` is not always same as `unsigned long`.
* Emplace in container instead of insert for performance.
* Do not slice derived type `SecKey` on base one `PubKey`.
* Use `make_{unique|shared}` and wrappers for exception safety and performance.

Unfortunately, can't check changes via tests, as have Windows machine.
Could you, please, check test results for me :)?

Also, using some CI tool like https://travis-ci.org/ + pull request hook make tests
checking much more easier and disallows merging of broken changes.

Signed-off-by: Dmitry Tsarevich <dimhotepus@gmail.com>

### CODE REVIEW

**Comment by faberga** [comment]
@dimhotepus Thank you for the bug fix suggestions.
Since we are readying our v1.1.0 release, if you agree I will incorporate your changes in this release and credit the contribution to you using your sign-off signature.

Thank you
-Flavio

**Comment by dimhotepus** [comment]
@faberga Thank you. 

A little note, I haven't tested my changes, so, please, run test suite on them. Some tests may be broken due to the fact we don't hide logical problems in notes now.

**Comment by victorshoup** [comment]
Note that my PR victor_initial_CKKS_review fixed one of the LogicError non-throw bugs in norms.cpp specifically, at line 503.  Also note that victor_initial_CKKS_review also corrected the condition at line 502.  So please be careful to ensure that the bug fix at line 502 remains intact.  Lines 502-503 should read:

  if (!(palg.getP() == -1 && palg.getPow2() >= 2 && sz <= m / 2))
    throw LogicError("bad args to CKKS_canonicalEmbedding");

Note the <= (which replaces <, which was incorrect).

For some reason, I didn't look for other  LogicError non-throw bugs when I fixed that one.  Also note that NTL contains a function called LogicError which itself throws an exception...maybe this code was initially written assuming that function was called...that would explain the bug.

**Comment by faberga** [comment]
@dimhotepus @victorshoup We ported the fixes to our v1.1.0 release and are running our internal regression tests. Everything going well, we will prepare the public release today/tomorrow.

**Comment by faberga** [comment]
@dimhotepus Hi,
V1.1.0-beta.0 is now available and current. Can you rebase your PR so we can review, please?

Thank you.
Flavio

**Comment by dimhotepus** [comment]
@faberga Integrated latest changes, now pr is slim and simple.

**Comment by faberga** [comment]
Closing as this PR has been superceeded by more recent versions of HElib.

**Pull request closed without merging**
